spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}?characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
mybatis:
  type-aliases-package: com.ryan.project.imdb
  mapper-locations: mapper/*.xml

logging:
  level:
    root: info
    com.ryan.project.imdb.service.IMDBService: debug
